version: '3'
services:
  backend:
    image: 127.0.0.1:5000/backend:todo-backend
    container_name: backend
    networks:
      - todo
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: todos
    depends_on:
      - mysql
    ports:
      - 3000:3000
    restart: on-failure

  client:
    image: 127.0.0.1:5000/client:todo-client
    container_name: client
    networks:
      - todo
    environment:
      API_URL: http://backend:3000/api/
    ports:
      - 8080:80
    depends_on:
      - backend

  mysql:
    image: mysql:8.0
    container_name: mysql
    networks:
      - todo
    volumes:
      - todo-mysql-data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todos

volumes:
  todo-mysql-data:

networks:
  todo:
    driver: overlay